### ISSUE TITLE
Create Mongo Database

### ISSUE THREAD

**Issue by makiwumi** [KendraNeves/curbside#34]

**Comment by ricardoshaffer** [comment]
- ### **Layout**
     - _Backend folder_
          - _Models folder_: (Listing.js) contains Schema, tells the controller which fields to carry out functions.
                - _Controller_: defines methods for calling database functions 
          - _Routes folder > api folder_:
                -index.js: contains general instructions to use '/listings' as the URL to search the API.
                -listings.js: contains instructions to use certain routes for key commands, such as '/:id'  to get, pull,  & delete, and '/' to post & get. (Syncs with _Controller folder_)
          -__Scripts Folder__:
                -itemsSeeds.js: contains generic seeds to visual testing environment.
     - client folder_
          - _Src/utilities/ Folder_:
                - _API.js_: utilizes axios to retrieve data from the 'api/listings/' based on the _Controller_ commands. this is then exported to whichever component/page utilizing the information.
                - _search folder_: contains the content that operates the 'search' function, including 'sort by date' and searching the title of the listings.
